Repository Gullu16102001/QuickBloxAndroidKotlin, pull requests merged in 2020-10, with the labels that each got.

#1 New Readme file.
  Readme.md
Labels: hacoberfest-accepted

#2 Backdrop for splash screen
  backdrop1.jpg
Labels: good first issue, hacoberfest-accepted

#6 Adding background image
  background.jpg
Labels: good first issue, hacktoberfest-accepted

#7 Update Readme.md
  Readme.md
Labels: documentation, good first issue, hacktoberfest-accepted
